# This file was generated by GoReleaser. DO NOT EDIT.
class Jengo < Formula
  desc "Golang based CLI for Jenkins API."
  homepage "https://github.com/tkennes/jengo"
  version "1.3.11"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/tkennes/jengo/releases/download/v1.3.11/jengo_1.3.11_Darwin_x86_64.tar.gz"
    sha256 "13fc705e34b7cbcd08341b7ee327d275107581eef97e09318971051968718556"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/tkennes/jengo/releases/download/v1.3.11/jengo_1.3.11_Linux_x86_64.tar.gz"
    sha256 "3fa2944e618f41429c61065f135892c9cdae032dc66bc6c60c693188d1f156ad"
  end
  
  depends_on "go" => :build

  def install
    bin.install "jengo"
  end

  test do
    assert shell_output("#{bin}/jengo version")
  end
end
